#!/bin/bash

# on NC :
#     on boot
#     while true; do { echo -e 'HTTP/1.1 200 OK\r\n'; echo "NodeController"; } | nc -l 31830; done
# This script runs on GNs. Can be started at boot time or can be 
# exicuted when DHCP address is recieved. 
# Writes the NC IP to a file in tmp

echo "127.0.0.1" > /tmp/nc.ip

NC=true
while $NC; do
    addr=(`ip addr show | grep -P '\d+\.\d+\.\d+.\d+\/\d+' -o | grep -v 127.0.0.1 | cut -d '.' -f 1-3`)
    if [ $addr ]; then
        for ip in $addr.{1..254}; do
        #     if [ $count -eq 100 ]
            if [ $(ping -c 1 -W 1 $ip | grep 'received' | awk -F',' '{ print $2}' | awk '{ print $1}') -eq 1 ]; then
                if [ $(printf "HEAD / HTTP/1.0\r\n\r\n" | nc -n -i 1 $ip 31830 | grep -i "200\ OK" | wc -l) -eq 1 ]; then 
#                     echo "$ip NC found!"
                    NC=false
                    break
#                 else
#                     echo "$ip Not NC."
                fi
#             else
#                 echo "$ip Host Down."
            fi
        done
    else
#         echo "Waiting for IP address..."
        sleep 10
    fi
done
echo $ip > /tmp/nc.ip
