#! /bin/bash
### BEGIN INIT INFO
# Provides: tomcat
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Tomcat
# Description: This file starts and stops Tomcat server
#
### END INIT INFO
 
WAGGLE_DIR=/root
export PYTHONPATH=$PYTHONPATH:/root/waggle/core/frameworks/node/sensormodules/weatherwx0.3
 
case "$1" in
start)
su root -c $WAGGLE_DIR/bin/startup.sh
;;
stop)
su root -c $WAGGLE_DIR/bin/shutdown.sh
sleep 10
;;
restart)
su root -c $WAGGLE_DIR/bin/shutdown.sh
sleep 20
su root -c $WAGGLE_DIR/bin/startup.sh
;;
*)
echo "Usage: waggle {start|stop|restart}" >&2
exit 3
;;
esac
 
