#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

# we cannot properly synthesize LVM LV change events with udevadm trigger, so
# if we use LVM, we need to let it finish; otherwise we get missing LV symlinks
# (LP #1185394)
if [ -x /sbin/vgchange ]; then
    udevadm settle --timeout=121 || true
fi

# Stop udevd, we'll miss a few events while we run init, but we catch up
udevadm control --timeout=121 --exit || \
            echo "udev exit failed -- rc=$?"

# move the /dev tmpfs to the rootfs
mount -n -o move /dev ${rootmnt}/dev

# create a temporary symlink to the final /dev for other initramfs scripts
rm -rf /dev
ln -s ${rootmnt}/dev /dev

